In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

# a's type is numpy.ndarray (n-dimensional array)
print(type(a))

# the data type of the a's elements
print(a.dtype)

# a's shape (a 1-dimensional array of shape (3,) - 3 elements on one row)
print(a.shape)

# the first element of a
# a can be indexed as a list
print(a[0])

[1 2 3]
<class 'numpy.ndarray'>
int32
(3,)
1


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])

# b's shape is (2, 3) - 2 rows, 3 elements each
print(b.shape)

# b can be indexed as a normal list
print(b[0][2])

# specific indexing - equivalent with b[0][2]
print(b[0, 2])

(2, 3)
3
3


In [4]:
# transforms any input data in ndarray
c = np.asarray([(1, 2), (3, 4)])

print(type(c))
print(c.shape)
print(c)

<class 'numpy.ndarray'>
(2, 2)
[[1 2]
 [3 4]]


In [5]:
# creating an ndarray of a given shape full of 0
zero_array = np.zeros((3, 2))
print(zero_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
# creating an ndarray of a given shape full of 1
ones_array = np.ones((2, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [7]:
# creating an ndarray of a given shape full of a given value
constant_array = np.full((2, 2), 8)
print(constant_array)

[[8 8]
 [8 8]]


In [8]:
# creates the identity matrix of the given size
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# creates a ndarray with random values
# evenly distributed between [0, 1)
random_array = np.random.random((1, 2))
print(random_array)

[[0.44280401 0.19620149]]


In [10]:
mu, sigma = 1, 0.1
# creates a ndarray with random values of
# Gaussian distribution with mean mu and standard deviation sigma
gaussian_random = np.random.normal(mu, sigma, (3, 6))
print(gaussian_random)

[[0.87222566 1.01352021 0.91363714 1.05911727 0.96514352 1.18474232]
 [0.85525028 1.15754103 1.01616265 1.05008284 1.04050419 0.92990581]
 [0.99028055 1.05284509 1.04760604 0.86324846 0.85307817 0.93088194]]


In [11]:
# creates a ndarray of the first n natural values
first_5 = np.arange(5)
print(first_5)#%%



[0 1 2 3 4]
