In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

### Sum by elements

In [3]:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


### Difference by elements

In [4]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


### Multiply by elements

In [5]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


### Division by elements

In [6]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Square root by elements

In [7]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Power by elements

In [8]:
my_array = np.arange(5)
powered = np.power(my_array, 3)
print(powered)

[ 0  1  8 27 64]


### Multiplying with a scalar

In [9]:
v = np.array([9, 10])
w = np.array([11, 12])

# array * array
print(v.dot(w))
print(np.dot(v, w))

# matrix * array
print(np.matmul(x, v))

# matrix * matrix
print(np.matmul(x, y))

219
219
[29 67]
[[19 22]
 [43 50]]


## Matrix operations

### Transpose & inverse

In [10]:
# matrix transpose
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array.T)

# matrix inverse
my_array = np.array([[1., 2.], [3., 4.]])
print(np.linalg.inv(my_array))

[[1 4]
 [2 5]
 [3 6]]
[[-2.   1. ]
 [ 1.5 -0.5]]


### Sum on specific dimension

In [11]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

# we can specify more axis
print(np.sum(x, axis=(0, 1)))

10
[4 6]
[3 7]
10


### Mean on specific dimension

In [12]:
y = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
              [[1, 2, 3, 4], [5, 6, 7, 8]],
              [[1, 2, 3, 4], [5, 6, 7, 8]]])
print(y.shape)
print(y)

print()

print(np.mean(y, axis=0))
print(np.mean(y, axis=1))

(3, 2, 4)
[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[3. 4. 5. 6.]
 [3. 4. 5. 6.]
 [3. 4. 5. 6.]]


### The index of the maximum element on each line

In [13]:
z = np.array([[10, 12, 5], [17, 11, 19]])
print(np.argmax(z, axis=1))

[1 2]
